### PR TITLE
adding AddressRangeIPv6

### PR DESCRIPTION
**Pull request by bluelineXY**

### CODE REVIEW

**Comment by bluelineXY** [comment]
Hi, 
is there any issue with commiting this code ? 
if so please let me know how to improve it.

**Comment by bluelineXY** [comment]
I had to add some changes, suggested by a contributer to the code. 
Now the AddressRangeIPv6 support should be more complete.

**Comment by bluelineXY** [comment]
Hi,
i had test with a iptables fw.
Would it help if i provide the xml or do you need something else ?

Br,

Mario


Am 2018-04-19 17:41, schrieb Sirius Bakke:

**Comment by sirius** [comment]
Please send a iptables fw xml file and desired output. Thank you for submitting code. I'll probably have to modify the other compilers before a new release is made.

**Pull request merged**
